[server]
headless = true
enableCORS = false

[theme]
base = "light"
primaryColor = "#1f77ff"

[client]
toolbarMode = "viewer"

[browser]
gatherUsageStats = false

[ui]
hideTopBar = false

[layout]
wideMode = true

